# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches:
      - main
      - 'v[0-9]+'
  pull_request:
    branches:
      - main
      - 'v[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"

      - name: Build
        run: go build -v main.go

      - name: Test
        run: go test -v ./...
  release:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/v'))
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Check semrelrc file
        run: cat .semrelrc

      - name: Run go-semantic-release
        uses: go-semantic-release/action@v1
        with:
          provider: github
          github-token: ${{ secrets.GITHUB_TOKEN }}













