name: Go CI/CD

on:
  push:
    branches:
      - main
      - '[0-9]+.x'   # e.g. 1.x, 2.x
  pull_request:

permissions:
  contents: read # for checkout

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"

      - name: Build
        run: go build -v main.go

      - name: Test
        run: go test -v ./...

  lint-pr-title:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v5
      - run: npm install @commitlint/{config-conventional,cli}
      - run: echo "${{ github.event.pull_request.title }}" | npx commitlint --config commitlint.config.js
        env:
          GITHUB_REF_NAME: ${{ github.event.pull_request.base.ref }}

  release:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write      # For pushing tags
      issues: write        # For creating issues
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Release
        uses: codfish/semantic-release-action@v4.0.0
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
